### ISSUE TITLE
Line of code breaks all of our tests

### ISSUE THREAD

**Issue by dexter-stpierre** [ackertyson/vue-dmresource#1]
The behavior on [this](https://github.com/ackertyson/vue-dmresource/blob/master/src/index.coffee#L4) line of code breaks our tests as it looks for a window.vue object when in test and we are now running our tests on the command line

**Comment by ackertyson** [comment]
Yeah, my original conditional check there was pretty lazy. I'll take a look. In the meantime, could you mock a global `window.Vue` in your test setup? Would at least get your tests up and working in the short term...

**Comment by ackertyson** [comment]
...though that would prolly break the bootstrap process. Nevermind. I'm looking at this now...

**Comment by dexter-stpierre** [comment]
No worries! I submitted a pull request that will probably fix the issue.. It just confirms that the `window.Vue` object exists

**Comment by ackertyson** [comment]
Published to NPM as v0.6.0

**Comment by ackertyson** [comment]
...except it would probably help if I rebuild the src first! Now available as v0.6.1

**Comment by dexter-stpierre** [comment]
Awesome, thank you!
